# -*- coding: utf-8 -*-
"""2025.11.9西南联大内迁.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oF3oN8arZX3xPqX9mk2ec96WhnilCCDt
"""

import pandas as pd
import folium

# 读取数据
url = "/content/西南联大内迁路线数据.csv"  # 请替换为实际文件路径或URL
df = pd.read_csv(url)

# 创建底图，初始定位在中国中部
m = folium.Map(location=[28.0, 106.0], zoom_start=5)

# 定义颜色映射
color_map = {
    "海陆并用": "blue",
    "湘黔滇步行团": "red"
}

# 按队伍分组绘制路线
for team, group in df.groupby('team'):
    route_name = group['route_name'].iloc[0]
    color = color_map[route_name]

    # 提取路线点
    locations = group[['latitude', 'longitude']].values.tolist()

    # 绘制路线
    folium.PolyLine(
        locations=locations,
        color=color,
        weight=3,
        opacity=0.7,
        tooltip=route_name
    ).add_to(m)

    # 绘制每个地点标记
    for _, row in group.iterrows():
        popup_text = f"<b>{row['location_name']}</b><br>日期: {row['date']}<br>说明: {row['description']}"
        folium.CircleMarker(
            location=[row['latitude'], row['longitude']],
            radius=6,
            color=color,
            fill=True,
            fill_color=color,
            popup=folium.Popup(popup_text, max_width=300)
        ).add_to(m)

# 添加图例
legend_html = '''
<div style="position: fixed;
            top: 10px; left: 50px; width: 180px; height: 80px;
            background-color: white; border:2px solid grey; z-index:9999;
            font-size:14px; padding: 10px">
     <p><span style="color: blue;">●</span> 海陆并用</p>
     <p><span style="color: red;">●</span> 湘黔滇步行团</p>
</div>
'''
m.get_root().html.add_child(folium.Element(legend_html))

# 保存为HTML文件
m.save('西南联大内迁路线图.html')

# 在Colab中显示地图
m

import pandas as pd
import folium
from folium.plugins import MeasureControl

# 读取数据
url = "/content/西南联大内迁路线数据.csv"  # 请替换为你的实际数据URL
df = pd.read_csv(url)

# 创建底图，初始中心点设为长沙
m = folium.Map(
    location=[28.23, 112.94],
    zoom_start=6,
    tiles='OpenStreetMap'
)

# 定义颜色映射
color_map = {
    '海陆并用': 'blue',
    '湘黔滇步行团': 'red'
}

# 为每条路线创建 FeatureGroup，便于控制显示/隐藏
feature_groups = {}

for route_name in df['route_name'].unique():
    fg = folium.FeatureGroup(name=route_name, show=False)
    feature_groups[route_name] = fg

# 添加路线和标记点
for idx, row in df.iterrows():
    route_name = row['route_name']
    color = color_map[route_name]

    # 创建格式化的弹出窗口内容
    popup_text = f"""
    <div style="
        font-family: Arial, sans-serif;
        min-width: 200px;
        line-height: 1.4;
    ">
        <div style="
            background-color: {color};
            color: white;
            padding: 8px 12px;
            margin: -10px -10px 8px -10px;
            border-radius: 5px 5px 0 0;
            font-weight: bold;
            font-size: 14px;
        ">
            {row['location_name']}
        </div>
        <div style="padding: 0 5px;">
    """

    if pd.notna(row['date']):
        popup_text += f"""
            <div style="margin: 8px 0;">
                <span style="font-weight: bold; color: #333;">📅 日期:</span><br>
                <span style="color: #666; margin-left: 8px;">{row['date']}</span>
            </div>
        """

    if pd.notna(row['description']):
        popup_text += f"""
            <div style="margin: 8px 0;">
                <span style="font-weight: bold; color: #333;">📝 描述:</span><br>
                <span style="color: #666; margin-left: 8px;">{row['description']}</span>
            </div>
        """

    popup_text += """
        </div>
    </div>
    """

    # 添加城市标记点
    folium.CircleMarker(
        location=[row['latitude'], row['longitude']],
        radius=6,
        popup=folium.Popup(popup_text, max_width=300),
        tooltip=row['location_name'],
        color=color,
        fillColor=color,
        fillOpacity=0.7
    ).add_to(feature_groups[route_name])

    # 添加路线（连接连续的点）
    route_df = df[df['route_name'] == route_name].sort_values('sequence')
    locations = list(zip(route_df['latitude'], route_df['longitude']))

    folium.PolyLine(
        locations=locations,
        color=color,
        weight=3,
        opacity=0.7,
        tooltip=route_name
    ).add_to(feature_groups[route_name])

# 将所有 FeatureGroup 添加到地图
for fg in feature_groups.values():
    fg.add_to(m)

# 添加图层控制
folium.LayerControl(collapsed=False).add_to(m)

# 添加测量工具
m.add_child(MeasureControl())

# 保存为 HTML 文件
m.save('西南联大内迁路线图_改进.html')

# 在 Colab 中显示地图
print("地图已生成！点击标记点查看详细信息。")
m

import pandas as pd
import folium
from folium import plugins
import branca.colormap as cm

# 读取数据
df = pd.read_csv('/content/西南联大内迁路线数据.csv')

# 创建底图，初始定位在中国中部
m = folium.Map(location=[28.0, 106.0], zoom_start=5)

# 定义颜色映射
color_map = {
    "海陆并用": "blue",
    "湘黔滇步行团": "red"
}

# 为每条路线创建动态时间线
for team, group in df.groupby('team'):
    route_name = group['route_name'].iloc[0]
    color = color_map[route_name]

    # 按sequence排序确保正确顺序
    group = group.sort_values('sequence')

    # 提取路线点
    locations = group[['latitude', 'longitude']].values.tolist()

    # 为时间线功能准备数据
    features = []
    for idx, row in group.iterrows():
        feature = {
            'type': 'Feature',
            'geometry': {
                'type': 'Point',
                'coordinates': [row['longitude'], row['latitude']]
            },
            'properties': {
                'time': row['date'] if pd.notna(row['date']) else '日期不详',
                'popup': f"<b>{row['location_name']}</b><br>队伍: {route_name}<br>日期: {row['date']}<br>说明: {row['description']}",
                'icon': 'circle',
                'iconstyle': {
                    'fillColor': color,
                    'fillOpacity': 0.8,
                    'stroke': 'true',
                    'radius': 6
                }
            }
        }
        features.append(feature)

    # 添加时间线
    plugins.TimestampedGeoJson(
        {
            'type': 'FeatureCollection',
            'features': features
        },
        period='P1M',  # 时间间隔为1个月
        add_last_point=True,
        auto_play=False,
        loop=False,
        max_speed=1,
        loop_button=True,
        date_options='YYYY年MM月',
        time_slider_drag_update=True,
        duration='P1M'
    ).add_to(m)

    # 同时保留静态路线作为参考
    folium.PolyLine(
        locations=locations,
        color=color,
        weight=2,
        opacity=0.5,
        tooltip=f"{route_name} (完整路线)",
        dash_array='5'
    ).add_to(m)

# 添加图例
legend_html = '''
<div style="position: fixed;
            top: 10px; left: 50px; width: 200px; height: 90px;
            background-color: white; border:2px solid grey; z-index:9999;
            font-size:14px; padding: 10px; border-radius: 5px;">
     <p style="margin: 2px 0;"><span style="color: blue;">●</span> 海陆并用</p>
     <p style="margin: 2px 0;"><span style="color: red;">●</span> 湘黔滇步行团</p>
     <p style="margin: 5px 0; font-size: 12px; color: #666;">使用时间轴控件播放动画</p>
</div>
'''
m.get_root().html.add_child(folium.Element(legend_html))

# 添加标题
title_html = '''
             <h3 align="center" style="font-size:16px; margin: 0; padding: 5px;">
             <b>西南联大内迁路线动态图 (1938年)</b></h3>
             '''
m.get_root().html.add_child(folium.Element(title_html))

# 保存为HTML文件
m.save('/content/西南联大内迁动态路线图.html')

print("动态路线图已生成！文件保存在：/content/西南联大内迁动态路线图.html")
print("使用地图左下角的时间轴控件可以播放路线动画")

# 在Colab中显示地图
m